name: push-image

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      COMMIT_MESSAGE: ${{ steps.commit_message.outputs.value }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Store the first line of commit message
        id: commit_message
        run: echo "value=hoge" >> $GITHUB_OUTPUT

  dispatch:
    # needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: shell
        run: echo "${{ needs.setup.outputs.COMMIT_MESSAGE }}"
